name: Testing PR Edit

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking if this runs on edited PR.
        env:
          eve: ${{ github.event.pull_request.number }}
        run: echo This runs for edited section - $eve
