name: Testing PR Edit

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking if this runs on edited PR.
        env:
          PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
          PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
        run: echo This runs for edited section - $PULL_REQUEST_BODY
