name: Testing PR Edit

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking if this runs on edited PR.
        env:
          DESC: ${{ github.event.description }}
        run: echo This runs for edited section - $DESC
      - name: Checking for Body var.
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          echo This runs for event - $BODY
      - name: Testing for github event for pull request.
        env:
          PR: ${{ github.event.pull_request.head.sha }}
        run: echo Github event PR - $PR
      
  
