name: Python Script
    
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: runner-linux01
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Dependencies.
        run: |
            python -m pip install requests
      - name: Run Script
        run: |
            python work.py
